[package]
name = "ntex"
version = "0.1.0"
edition = "2021"

[dependencies]
ntex = { version = "2.0", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.8"
log = "0.4"